---
- name: Install chezmoi
  community.general.pacman:
    name: chezmoi
    state: present
  when: dotfiles.url is defined

- name: Init chezmoi repo locally
  ansible.builtin.command: chezmoi init {{ dotfiles.url }}
  when: dotfiles.url is defined
  args:
    creates: /home/{{ user.name }}/.local/share/chezmoi
