---
- name: Install amd microcode
  community.general.pacman:
    name: amd-ucode
    state: present
  when: "'AuthenticAMD' in ansible_processor"
  notify:
    - Rebuild grub

- name: Install intel microcode
  community.general.pacman:
    name: intel-ucode
    state: present
  when: "'GenuineIntel' in ansible_processor"
  notify:
    - Rebuild grub
