---
- name: Install ssh
  community.general.pacman:
    name:
      - openssh

- name: Create user-level systemd directory
  ansible.builtin.file:
    path: /home/{{ user.name }}/.config/systemd/user
    recurse: true
    state: directory

- name: Copy ssh-agent systemd config
  ansible.builtin.copy:
    src: ssh-agent.service
    dest: /home/{{ user.name }}/.config/systemd/user/ssh-agent.service
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0644
