---
- name: Install i3
  community.general.pacman:
    name:
      - i3-wm
      - i3blocks
      - i3lock
      - i3status
    state: present

- name: Install py3status
  community.general.pacman:
    name: py3status
    state: present

- name: Verify that default applications file exists
  ansible.builtin.file:
    path: /etc/xdg/mimeapps.list
    state: touch

- name: Verify header in default applications file
  ansible.builtin.lineinfile:
    dest: /etc/xdg/mimeapps.list
    state: present
    line: "[Default Applications]"
    insertbefore: BOF

- name: Install rofi
  community.general.pacman:
    name: rofi
    state: present

- name: Install i3-wm for rofi window switching
  community.general.pacman:
    name: i3-wm
    state: present

- name: Create user config directory for i3
  ansible.builtin.file:
    path: /home/{{ user.name }}/.config/i3
    recurse: true
    state: directory

- name: Copy i3 config
  ansible.builtin.copy:
    src: config
    dest: /home/{{ user.name }}/.config/i3/config
