---
- name: Install tailscale
  community.general.pacman:
    name: tailscale
    state: present

- name: Ensure ip forwarding config file exists
  ansible.builtin.file:
    path: /etc/sysctl.conf
    state: touch
    owner: root
    group: root
    mode: 0644
  when: vpn.exit_node

- name: Add ipv4 forwarding
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    state: present
    regexp: ^net.ipv4.ip_forward =
    line: net.ipv4.ip_forward = 1
  notify: Enable ip forwarding
  when: vpn.exit_node and vpn.ipv4

- name: Add ipv6 forwarding
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    state: present
    regexp: ^net.ipv6.ip_forward =
    line: net.ipv6.ip_forward = 1
  notify: Enable ip forwarding
  when: vpn.exit_node and vpn.ipv6
