---
- name: Set timezone
  ansible.builtin.file:
    src: /usr/share/zoneinfo/{{ user.timezone }}
    dest: /etc/localtime
    owner: root
    group: root
    state: link
  tags:
    - time

- name: Enable systemd-timesyncd service
  ansible.builtin.service:
    name: systemd-timesyncd.service
    enabled: true
  tags:
    - time

- name: Install networkmanager
  community.general.pacman:
    name:
      - networkmanager
    state: present
  tags:
    - network

- name: Enable networkmanager service
  ansible.builtin.service:
    name: NetworkManager.service
    enabled: true
  tags:
    - network
