---
- name: Install universal base packages
  community.general.pacman:
    name: "{{ base_packages }}"
    state: present
  tags:
    - packages

- name: Create pacman hook directory
  ansible.builtin.file:
    path: /etc/pacman.d/hooks
    state: directory
  tags:
    - packages
