---
- name: Install Bash
  community.general.pacman:
    name:
      - bash
      - bash-completion
    state: present
  tags:
    - shell

- name: Install ZSH
  community.general.pacman:
    name:
      - zsh
      - zsh-completions
    state: present
  tags:
    - shell
