---
- name: Install sudo
  community.general.pacman:
    name: sudo
    state: present
  tags:
    - sudo

- name: Copy sudo configuration
  ansible.builtin.template:
    src: sudoers.j2
    dest: "/etc/sudoers.d/00_{{ user.name }}"
    mode: 0440
    validate: visudo --check --file %s
  tags:
    - sudo
