---
- name: Create user group
  ansible.builtin.group:
    name: "{{ user.name }}"
    state: present
  tags:
    - user

- name: Create user and assign to group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: "{{ user.name }}"
    password: "{{ user.password | default('password', true) | password_hash('sha512') }}"
    shell: /usr/bin/{{ user.shell }}
    update_password: on_create
    append: true
  tags:
    - user

- name: Create user socket directory
  ansible.builtin.file:
    path: /run/user/{{ user.uid }}
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0700
  tags:
    - user

- name: Start user systemd instance
  ansible.builtin.service:
    name: user@{{ user.uid }}
    state: started
  notify: Stop systemd per-user instance
  tags:
    - user
