---
- name: Install fontconfig
  community.general.pacman:
    name: fontconfig
    state: present

- name: Push font substitutions
  ansible.builtin.copy:
    src: local.conf
    dest: /etc/fonts/local.conf

- name: Install base fonts
  community.general.pacman:
    name: "{{ base_fonts }}"
    state: present
